language: csharp
solution: GeneticAlgorithms.sln
install:
  - nuget restore GeneticAlgorithms.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GeneticAlgorithms.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Erikmafo.GeneticAlgorithmsTests/bin/Release/Erikmafo.GeneticAlgorithmsTests.dll
